import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="//at.alicdn.com/t/c/font_4926970_rito8jdlqxq.js"></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex items-center justify-center h-16 border-b border-gray-50 shadow-md">
          <h1 className="text-2xl font-bold">前端技巧收集</h1>
        </header>
        <div className="flex flex-col items-center justify-center h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
